

<?php $__env->startSection('content'); ?>
<!DOCTYPE html>
<html lang="en-US">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="profile" href="http://gmpg.org/xfn/11">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<title>PVD Metal Sheets &#8211; Metal Craft Studio</title>
<!--==================== ti breadcrumb section ====================-->

<div class="bs-breadcrumb-section" style='background-image: linear-gradient(132deg, #ffffffc4 50% ,transparent 50%),url("");        background-attachment: scroll  
;'> 
  <div class="overlay" style="background: #ffffffb3" );>
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-sm-12">
			   <div class="bs-breadcrumb-title"><h1 class="page-title">PVD Metal Sheets</h1></div>        </div>
      </div>
    </div>
  </div>
</div>
<div class="clearfix"></div>
<!--==================== main content section ====================-->
<main id="content">
    <div class="container">
      <div class="row">
		<!-- Blog Area -->
						<div class="col-md-9">
			
<h2 class="wp-block-heading has-text-align-left">Coming Soon</h2>



<div class="wp-block-buttons is-layout-flex">
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="<?php echo e(url('Contect')); ?>">Contact Now</a></div>
</div>
			</div>
			<!--Sidebar Area-->
			<aside class="col-md-3">
				
<aside id="secondary" class="widget-area" role="complementary">
	<div id="sidebar-right" class="bs-sidebar">
		<div id="block-7" class="bs-widget widget_block widget_search"><form role="search" method="get" action="https://metalcraftstudio.com/" class="wp-block-search__button-outside wp-block-search__text-button wp-block-search"><label for="wp-block-search__input-2" class="wp-block-search__label" >Search</label><div class="wp-block-search__inside-wrapper " ><input type="search" id="wp-block-search__input-2" class="wp-block-search__input" name="s" value="" placeholder=""  required /><button type="submit" class="wp-block-search__button wp-element-button"  >Search</button></div></form></div><div id="block-8" class="bs-widget widget_block">
<div class="wp-block-group is-layout-flow"><div class="wp-block-group__inner-container">
<h2 class="wp-block-heading">Recent Product<strong>s</strong></h2>


<ul>
<li><a href="<?php echo e(url('pvd-louver-panels')); ?>" data-type="page" data-id="236">PVD Louver Panels</a></li>



<li><a href="<?php echo e(url('pvd-metal-sheets')); ?>" data-type="page" data-id="238">PVD Metal Sheets</a></li>



<li><a href="<?php echo e(url('stainless-steel-decorative-profiles')); ?>" data-type="page" data-id="371">Stainless Steel Decorative Profiles</a></li>



<li><a href="<?php echo e(url('textured-sheets')); ?>" data-type="page" data-id="369">Textured Sheets</a></li>
</ul>



<h2 class="wp-block-heading"><br></h2>
</div></div>
</div>	</div>
</aside><!-- #secondary -->
			</aside>
						<!--Sidebar Area-->
			</div>
		</div>
	</div>
</main>
<!--==================== industryup-FOOTER AREA ====================-->
  
</body>
</html>
<?php $__env->stopSection(); ?>
<!--Generated by Endurance Page Cache-->
<?php echo $__env->make('layouts.hedder', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH C:\xampp\htdocs\auth\resources\views/pvd-metal-sheets.blade.php ENDPATH**/ ?>